version: "3.2"
services:
  gym_backend:
    build: ./gym_backend        
    ports:
      - "8000:8000"
    volumes:
      - ./gym_backend:/gym_backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./gym_web_front
    ports:
      - "3000:3000"
    volumes:
      - ./gym_web_front:/gym_web_front

