# Generated by Django 4.1.3 on 2022-12-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Name", max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registrationDate",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("limit", models.IntegerField(default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Name", max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "registrationDate",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "attribute_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("hour", models.TimeField()),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.instructor",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="members", to="api.student"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("level", models.IntegerField(default=1, null=True)),
                (
                    "subgroups",
                    models.ManyToManyField(
                        blank=True, related_name="subgroups", to="api.subgroup"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                (
                    "attendance",
                    models.ManyToManyField(
                        blank=True, related_name="attendance", to="api.attendance"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="attendance_members", to="api.student"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="subgroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.subgroup",
            ),
        ),
    ]
