# Generated by Django 4.1.3 on 2022-11-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_group_level_alter_group_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AddField(
            model_name='dates',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
