# Generated by Django 4.1.3 on 2022-11-22 21:44

import api.custom_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instructor_room_student_second_name_alter_group_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='days',
        ),
        migrations.RemoveField(
            model_name='group',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='group',
            name='room',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', api.custom_fields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('hour', models.TimeField()),
                ('repeat', api.custom_fields.FrequencyField(choices=[('1', 'weekly'), ('2', 'biweekly'), ('3', 'monthly')], max_length=1)),
                ('start', models.DateField(default=datetime.date(2022, 11, 22))),
                ('stop', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.ManyToManyField(related_name='events', to='api.event'),
        ),
    ]
