# Generated by Django 4.1.3 on 2022-11-22 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_group_days_remove_group_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
