# Generated by Django 4.1.3 on 2022-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dates_parentdata_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dates',
            name='rRule',
            field=models.CharField(default='', max_length=200),
        ),
    ]
