# Generated by Django 4.1.3 on 2022-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dates_allday_alter_dates_rrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='parentData',
            field=models.JSONField(default=None),
        ),
    ]
