# Generated by Django 4.1.3 on 2022-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dates_parentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='parentData',
            field=models.JSONField(default=None, null=True),
        ),
    ]
