# Generated by Django 4.1.3 on 2022-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dates_parentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='rRule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
