# Generated by Django 4.1.3 on 2022-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dates_rrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
