# Generated by Django 4.1.3 on 2022-11-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dates_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dates',
            old_name='notes',
            new_name='values',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='allDay',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='parentData',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='rRule',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='title',
        ),
    ]
