# Generated by Django 4.1.3 on 2022-11-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dates_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='time',
        ),
    ]
